services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wikiscrape

    network_mode: "bridge"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5

    volumes:
      - ${PWD}/db:/var/lib/postgresql/data


  scraper:
    image: "ghcr.io/crnvl/wikiscrape-scrape:latest"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: wikiscrape
      DB_HOST: localhost
      DB_PORT: 5432

    network_mode: "host"

    depends_on:
      database:
        condition: service_healthy
